#ifndef ROADMAP_DOWNLOAD_SETTINGS_H_
#define ROADMAP_DOWNLOAD_SETTINGS_H_
void roadmap_download_settings_show(void);
void roadmap_download_settings_init(void);
BOOL roadmap_download_settings_isEnabled(RoadMapConfigDescriptor descriptor);
BOOL roadmap_download_settings_isDownloadWazers(void);
BOOL roadmap_download_settings_isDownloadReports(void);
BOOL roadmap_download_settings_isDownloadTraffic(void);
#endif /*ROADMAP_DOWNLOAD_SETTINGS_H_*/
