#!/bin/bash
declare -a cydia
cydia=($CYDIA)

if [[ $1 == install || $1 == upgrade ]]; then
	if [[ ${CYDIA+@} ]]; then
		eval "echo 'finish:restart' >&${cydia[0]}"
	fi
fi

if [ -d /var/mobile/Library/.waze ] ; then
	if [ -f /var/mobile/Library/.waze/user ]; then
		mv /var/mobile/Library/.waze/user /tmp/.waze_user.bak
	fi
	if [ -f /var/mobile/Library/.waze/history ]; then
		mv /var/mobile/Library/.waze/history /tmp/.waze_history.bak
	fi
	rm -r /var/mobile/Library/.waze
fi

if [ -f /var/mobile/Library/.freemap/user ]; then
	mv /var/mobile/Library/.freemap/user /tmp/.waze_user.bak
fi
