/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_FreeMapNativeLocListener */

#ifndef _Included_com_waze_FreeMapNativeLocListener
#define _Included_com_waze_FreeMapNativeLocListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waze_FreeMapNativeLocListener
 * Method:    LocListenerCallbackNTV
 * Signature: (BIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeLocListener_LocListenerCallbackNTV
  (JNIEnv *, jobject, jbyte, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_waze_FreeMapNativeLocListener
 * Method:    SatteliteListenerCallbackNTV
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeLocListener_SatteliteListenerCallbackNTV
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_waze_FreeMapNativeLocListener
 * Method:    DilutionListenerCallbackNTV
 * Signature: (IDDD)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeLocListener_DilutionListenerCallbackNTV
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_FreeMapNativeLocListener_GpsStatusListener */

#ifndef _Included_com_waze_FreeMapNativeLocListener_GpsStatusListener
#define _Included_com_waze_FreeMapNativeLocListener_GpsStatusListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_FreeMapNativeLocListener_NativeLocation */

#ifndef _Included_com_waze_FreeMapNativeLocListener_NativeLocation
#define _Included_com_waze_FreeMapNativeLocListener_NativeLocation
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
