/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_FreeMapNativeSoundManager */

#ifndef _Included_com_waze_FreeMapNativeSoundManager
#define _Included_com_waze_FreeMapNativeSoundManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_FreeMapNativeSoundManager_MAX_PLAYERS_NUMBER
#define com_waze_FreeMapNativeSoundManager_MAX_PLAYERS_NUMBER 5L
/*
 * Class:     com_waze_FreeMapNativeSoundManager
 * Method:    InitSoundManagerNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeSoundManager_InitSoundManagerNTV
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_FreeMapNativeSoundManager_MediaPlayerQueued */

#ifndef _Included_com_waze_FreeMapNativeSoundManager_MediaPlayerQueued
#define _Included_com_waze_FreeMapNativeSoundManager_MediaPlayerQueued
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_FreeMapNativeSoundManager_PlayersCache */

#ifndef _Included_com_waze_FreeMapNativeSoundManager_PlayersCache
#define _Included_com_waze_FreeMapNativeSoundManager_PlayersCache
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_FreeMapNativeSoundManager_PlayersCache_DEFAULT_INITIAL_CAPACITY
#define com_waze_FreeMapNativeSoundManager_PlayersCache_DEFAULT_INITIAL_CAPACITY 16L
#undef com_waze_FreeMapNativeSoundManager_PlayersCache_MAXIMUM_CAPACITY
#define com_waze_FreeMapNativeSoundManager_PlayersCache_MAXIMUM_CAPACITY 1073741824L
#undef com_waze_FreeMapNativeSoundManager_PlayersCache_DEFAULT_LOAD_FACTOR
#define com_waze_FreeMapNativeSoundManager_PlayersCache_DEFAULT_LOAD_FACTOR 0.75f
#undef com_waze_FreeMapNativeSoundManager_PlayersCache_serialVersionUID
#define com_waze_FreeMapNativeSoundManager_PlayersCache_serialVersionUID 362498820763181265LL
#undef com_waze_FreeMapNativeSoundManager_PlayersCache_serialVersionUID
#define com_waze_FreeMapNativeSoundManager_PlayersCache_serialVersionUID 3801124242820219131LL
#ifdef __cplusplus
}
#endif
#endif
