/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_FreeMapNativeSoundManager */

#ifndef _Included_com_waze_FreeMapNativeSoundManager
#define _Included_com_waze_FreeMapNativeSoundManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_FreeMapNativeSoundManager_SOUND_BUFFERING_ENABLED
#define com_waze_FreeMapNativeSoundManager_SOUND_BUFFERING_ENABLED 0L
/*
 * Class:     com_waze_FreeMapNativeSoundManager
 * Method:    InitSoundManagerNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeSoundManager_InitSoundManagerNTV
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_FreeMapNativeSoundManager_WazeAudioPlayer */

#ifndef _Included_com_waze_FreeMapNativeSoundManager_WazeAudioPlayer
#define _Included_com_waze_FreeMapNativeSoundManager_WazeAudioPlayer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_FreeMapNativeSoundManager_WazeAudioPlayer_MIN_PRIORITY
#define com_waze_FreeMapNativeSoundManager_WazeAudioPlayer_MIN_PRIORITY 1L
#undef com_waze_FreeMapNativeSoundManager_WazeAudioPlayer_NORM_PRIORITY
#define com_waze_FreeMapNativeSoundManager_WazeAudioPlayer_NORM_PRIORITY 5L
#undef com_waze_FreeMapNativeSoundManager_WazeAudioPlayer_MAX_PRIORITY
#define com_waze_FreeMapNativeSoundManager_WazeAudioPlayer_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_FreeMapNativeSoundManager_WazeAudioPlayer_CompletionListener */

#ifndef _Included_com_waze_FreeMapNativeSoundManager_WazeAudioPlayer_CompletionListener
#define _Included_com_waze_FreeMapNativeSoundManager_WazeAudioPlayer_CompletionListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
