/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_FreeMapNativeManager */

#ifndef _Included_com_waze_FreeMapNativeManager
#define _Included_com_waze_FreeMapNativeManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_FreeMapNativeManager_NATIVE_THREAD_PRIORITY
#define com_waze_FreeMapNativeManager_NATIVE_THREAD_PRIORITY -18L
#undef com_waze_FreeMapNativeManager_CAMERA_PREVIEW_TIMEOUT
#define com_waze_FreeMapNativeManager_CAMERA_PREVIEW_TIMEOUT 30000LL
/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    NativeMsgDispatcherNTV
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_NativeMsgDispatcherNTV
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    InitNativeManagerNTV
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_InitNativeManagerNTV
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    AppStartNTV
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_AppStartNTV
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    AppShutDownNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_AppShutDownNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    ShowGpsDisabledWarningNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_ShowGpsDisabledWarningNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    BackLightMonitorResetNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_BackLightMonitorResetNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    SetUpgradeRunNTV
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_SetUpgradeRunNTV
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    SetBackgroundRunNTV
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_SetBackgroundRunNTV
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_FreeMapNativeManager_FreeMapUIEvent */

#ifndef _Included_com_waze_FreeMapNativeManager_FreeMapUIEvent
#define _Included_com_waze_FreeMapNativeManager_FreeMapUIEvent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_FreeMapNativeManager_FreeMapUIMsgDispatcher */

#ifndef _Included_com_waze_FreeMapNativeManager_FreeMapUIMsgDispatcher
#define _Included_com_waze_FreeMapNativeManager_FreeMapUIMsgDispatcher
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_FreeMapNativeManager_NativeThread */

#ifndef _Included_com_waze_FreeMapNativeManager_NativeThread
#define _Included_com_waze_FreeMapNativeManager_NativeThread
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
