/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_FreeMapNativeSoundManager */

#ifndef _Included_com_waze_FreeMapNativeSoundManager
#define _Included_com_waze_FreeMapNativeSoundManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waze_FreeMapNativeSoundManager
 * Method:    InitSoundManagerNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeSoundManager_InitSoundManagerNTV
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_FreeMapNativeSoundManager_WazeAudioPlayer */

#ifndef _Included_com_waze_FreeMapNativeSoundManager_WazeAudioPlayer
#define _Included_com_waze_FreeMapNativeSoundManager_WazeAudioPlayer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
