/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_FreeMapNativeTimerTask */

#ifndef _Included_com_waze_FreeMapNativeTimerTask
#define _Included_com_waze_FreeMapNativeTimerTask
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_FreeMapNativeTimerTask_VIRGIN
#define com_waze_FreeMapNativeTimerTask_VIRGIN 0L
#undef com_waze_FreeMapNativeTimerTask_SCHEDULED
#define com_waze_FreeMapNativeTimerTask_SCHEDULED 1L
#undef com_waze_FreeMapNativeTimerTask_EXECUTED
#define com_waze_FreeMapNativeTimerTask_EXECUTED 2L
#undef com_waze_FreeMapNativeTimerTask_CANCELLED
#define com_waze_FreeMapNativeTimerTask_CANCELLED 3L
#ifdef __cplusplus
}
#endif
#endif
