/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_FreeMapNativeCanvas */

#ifndef _Included_com_waze_FreeMapNativeCanvas
#define _Included_com_waze_FreeMapNativeCanvas
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_FreeMapNativeCanvas_WAZE_OGL_SWAP_BUFFERS_DELAY
#define com_waze_FreeMapNativeCanvas_WAZE_OGL_SWAP_BUFFERS_DELAY 10LL
#undef com_waze_FreeMapNativeCanvas_WAZE_OGL_RENDER_WAIT_TIMEOUT
#define com_waze_FreeMapNativeCanvas_WAZE_OGL_RENDER_WAIT_TIMEOUT 100LL
/*
 * Class:     com_waze_FreeMapNativeCanvas
 * Method:    InitCanvasNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeCanvas_InitCanvasNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_waze_FreeMapNativeCanvas
 * Method:    CanvasConfigureNTV
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeCanvas_CanvasConfigureNTV
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_waze_FreeMapNativeCanvas
 * Method:    CreateCanvasNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeCanvas_CreateCanvasNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_waze_FreeMapNativeCanvas
 * Method:    CanvasPrepareNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeCanvas_CanvasPrepareNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_waze_FreeMapNativeCanvas
 * Method:    CanvasOrientationUpdateNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeCanvas_CanvasOrientationUpdateNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_waze_FreeMapNativeCanvas
 * Method:    CanvasContextNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeCanvas_CanvasContextNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_waze_FreeMapNativeCanvas
 * Method:    CanvasRenderNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeCanvas_CanvasRenderNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_waze_FreeMapNativeCanvas
 * Method:    KeyDownHandlerNTV
 * Signature: (IZ[B)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeCanvas_KeyDownHandlerNTV
  (JNIEnv *, jobject, jint, jboolean, jbyteArray);

/*
 * Class:     com_waze_FreeMapNativeCanvas
 * Method:    MousePressedNTV
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeCanvas_MousePressedNTV
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_waze_FreeMapNativeCanvas
 * Method:    MouseReleasedNTV
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeCanvas_MouseReleasedNTV
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_waze_FreeMapNativeCanvas
 * Method:    MouseMovedNTV
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeCanvas_MouseMovedNTV
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
