/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_FreeMapNativeManager */

#ifndef _Included_com_waze_FreeMapNativeManager
#define _Included_com_waze_FreeMapNativeManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_FreeMapNativeManager_NATIVE_THREAD_PRIORITY
#define com_waze_FreeMapNativeManager_NATIVE_THREAD_PRIORITY -18L
#undef com_waze_FreeMapNativeManager_CAMERA_PREVIEW_TIMEOUT
#define com_waze_FreeMapNativeManager_CAMERA_PREVIEW_TIMEOUT 60000LL
#undef com_waze_FreeMapNativeManager_WAZE_WIDGET_ENABLED
#define com_waze_FreeMapNativeManager_WAZE_WIDGET_ENABLED 0L
#undef com_waze_FreeMapNativeManager_MEMORY_PROFILER_ENABLED
#define com_waze_FreeMapNativeManager_MEMORY_PROFILER_ENABLED 1L
#undef com_waze_FreeMapNativeManager_CPU_PROFILER_ENABLED
#define com_waze_FreeMapNativeManager_CPU_PROFILER_ENABLED 1L
#undef com_waze_FreeMapNativeManager_TEMPERATURE_PROFILER_ENABLED
#define com_waze_FreeMapNativeManager_TEMPERATURE_PROFILER_ENABLED 0L
#undef com_waze_FreeMapNativeManager_MEMORY_PROFILER_PERIOD
#define com_waze_FreeMapNativeManager_MEMORY_PROFILER_PERIOD 600000LL
#undef com_waze_FreeMapNativeManager_TEMPERATURE_PROFILER_PERIOD
#define com_waze_FreeMapNativeManager_TEMPERATURE_PROFILER_PERIOD 120000LL
#undef com_waze_FreeMapNativeManager_STORAGE_SPACE_LOW_BOUND
#define com_waze_FreeMapNativeManager_STORAGE_SPACE_LOW_BOUND 5000000LL
/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    UrlHandlerNTV
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_waze_FreeMapNativeManager_UrlHandlerNTV
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    NativeMsgDispatcherNTV
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_NativeMsgDispatcherNTV
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    InitNativeManagerNTV
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_InitNativeManagerNTV
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jstring);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    AppStartNTV
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_AppStartNTV
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    AppShutDownNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_AppShutDownNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    ShowGpsDisabledWarningNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_ShowGpsDisabledWarningNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    BackLightMonitorResetNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_BackLightMonitorResetNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    SetUpgradeRunNTV
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_SetUpgradeRunNTV
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    SetBackgroundRunNTV
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_SetBackgroundRunNTV
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    EditBoxCallbackNTV
 * Signature: (ILjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_EditBoxCallbackNTV
  (JNIEnv *, jobject, jint, jstring, jlong);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    TakePictureCallbackNTV
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_TakePictureCallbackNTV
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    EditBoxCheckTypingLockNTV
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_waze_FreeMapNativeManager_EditBoxCheckTypingLockNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_waze_FreeMapNativeManager
 * Method:    ConnectivityChangedNTV
 * Signature: (ZILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeManager_ConnectivityChangedNTV
  (JNIEnv *, jobject, jboolean, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_FreeMapNativeManager_CheckSDCardCallback */

#ifndef _Included_com_waze_FreeMapNativeManager_CheckSDCardCallback
#define _Included_com_waze_FreeMapNativeManager_CheckSDCardCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_FreeMapNativeManager_CompatabilityWrapper */

#ifndef _Included_com_waze_FreeMapNativeManager_CompatabilityWrapper
#define _Included_com_waze_FreeMapNativeManager_CompatabilityWrapper
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_FreeMapNativeManager_FreeMapUIEvent */

#ifndef _Included_com_waze_FreeMapNativeManager_FreeMapUIEvent
#define _Included_com_waze_FreeMapNativeManager_FreeMapUIEvent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_FreeMapNativeManager_FreeMapUIMsgDispatcher */

#ifndef _Included_com_waze_FreeMapNativeManager_FreeMapUIMsgDispatcher
#define _Included_com_waze_FreeMapNativeManager_FreeMapUIMsgDispatcher
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_FreeMapNativeManager_NativeThread */

#ifndef _Included_com_waze_FreeMapNativeManager_NativeThread
#define _Included_com_waze_FreeMapNativeManager_NativeThread
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
