/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_FreeMapNativeTimerManager */

#ifndef _Included_com_waze_FreeMapNativeTimerManager
#define _Included_com_waze_FreeMapNativeTimerManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_FreeMapNativeTimerManager_FREMAP_MAX_TASK_COUNT
#define com_waze_FreeMapNativeTimerManager_FREMAP_MAX_TASK_COUNT 24L
/*
 * Class:     com_waze_FreeMapNativeTimerManager
 * Method:    InitTimerManagerNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_FreeMapNativeTimerManager_InitTimerManagerNTV
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
