/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_WazeLog */

#ifndef _Included_com_waze_WazeLog
#define _Included_com_waze_WazeLog
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_WazeLog_DEBUG_LVL
#define com_waze_WazeLog_DEBUG_LVL 1L
#undef com_waze_WazeLog_INFO_LVL
#define com_waze_WazeLog_INFO_LVL 2L
#undef com_waze_WazeLog_WARNING_LVL
#define com_waze_WazeLog_WARNING_LVL 3L
#undef com_waze_WazeLog_ERROR_LVL
#define com_waze_WazeLog_ERROR_LVL 4L
#undef com_waze_WazeLog_FATAL_LVL
#define com_waze_WazeLog_FATAL_LVL 5L
/*
 * Class:     com_waze_WazeLog
 * Method:    WazeLogNTV
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_waze_WazeLog_WazeLogNTV
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_WazeLog_LogCatMonitor */

#ifndef _Included_com_waze_WazeLog_LogCatMonitor
#define _Included_com_waze_WazeLog_LogCatMonitor
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_WazeLog_LogCatMonitor_MIN_PRIORITY
#define com_waze_WazeLog_LogCatMonitor_MIN_PRIORITY 1L
#undef com_waze_WazeLog_LogCatMonitor_NORM_PRIORITY
#define com_waze_WazeLog_LogCatMonitor_NORM_PRIORITY 5L
#undef com_waze_WazeLog_LogCatMonitor_MAX_PRIORITY
#define com_waze_WazeLog_LogCatMonitor_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
