/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_WazeTtsManager */

#ifndef _Included_com_waze_WazeTtsManager
#define _Included_com_waze_WazeTtsManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waze_WazeTtsManager
 * Method:    InitTtsManagerNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_WazeTtsManager_InitTtsManagerNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_waze_WazeTtsManager
 * Method:    TtsManagerCallbackNTV
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_waze_WazeTtsManager_TtsManagerCallbackNTV
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_WazeTtsManager_UtteranceCompletedListener */

#ifndef _Included_com_waze_WazeTtsManager_UtteranceCompletedListener
#define _Included_com_waze_WazeTtsManager_UtteranceCompletedListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
