/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_WazeMenuManager */

#ifndef _Included_com_waze_WazeMenuManager
#define _Included_com_waze_WazeMenuManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_WazeMenuManager_WAZE_OPT_MENU_ITEMS_MAXNUM
#define com_waze_WazeMenuManager_WAZE_OPT_MENU_ITEMS_MAXNUM 10L
#undef com_waze_WazeMenuManager_WAZE_OPT_MENU_DRIVE_TO_ID
#define com_waze_WazeMenuManager_WAZE_OPT_MENU_DRIVE_TO_ID 0L
#undef com_waze_WazeMenuManager_WAZE_OPT_MENU_REPORT_ID
#define com_waze_WazeMenuManager_WAZE_OPT_MENU_REPORT_ID 1L
#undef com_waze_WazeMenuManager_WAZE_OPT_MENU_ME_ON_MAP_ID
#define com_waze_WazeMenuManager_WAZE_OPT_MENU_ME_ON_MAP_ID 2L
#undef com_waze_WazeMenuManager_WAZE_OPT_MENU_EVENTS_ID
#define com_waze_WazeMenuManager_WAZE_OPT_MENU_EVENTS_ID 3L
#undef com_waze_WazeMenuManager_WAZE_OPT_MENU_SETTINGS_ID
#define com_waze_WazeMenuManager_WAZE_OPT_MENU_SETTINGS_ID 4L
#undef com_waze_WazeMenuManager_NATIVE_MSG_CATEGORY_MENU
#define com_waze_WazeMenuManager_NATIVE_MSG_CATEGORY_MENU 524288L
/*
 * Class:     com_waze_WazeMenuManager
 * Method:    InitMenuManagerNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_WazeMenuManager_InitMenuManagerNTV
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_WazeMenuManager_WazeMenuItem */

#ifndef _Included_com_waze_WazeMenuManager_WazeMenuItem
#define _Included_com_waze_WazeMenuManager_WazeMenuItem
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
