/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_WazeSoundRecorder */

#ifndef _Included_com_waze_WazeSoundRecorder
#define _Included_com_waze_WazeSoundRecorder
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_WazeSoundRecorder_MAX_FILE_SIZE_BYTES
#define com_waze_WazeSoundRecorder_MAX_FILE_SIZE_BYTES 100000LL
#undef com_waze_WazeSoundRecorder_SAMPLING_RATE
#define com_waze_WazeSoundRecorder_SAMPLING_RATE 16000L
/*
 * Class:     com_waze_WazeSoundRecorder
 * Method:    InitSoundRecorderNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_WazeSoundRecorder_InitSoundRecorderNTV
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_WazeSoundRecorder_CompatabilityWrapper */

#ifndef _Included_com_waze_WazeSoundRecorder_CompatabilityWrapper
#define _Included_com_waze_WazeSoundRecorder_CompatabilityWrapper
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_WazeSoundRecorder_OnErrorListener */

#ifndef _Included_com_waze_WazeSoundRecorder_OnErrorListener
#define _Included_com_waze_WazeSoundRecorder_OnErrorListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_WazeSoundRecorder_OnInfoListener */

#ifndef _Included_com_waze_WazeSoundRecorder_OnInfoListener
#define _Included_com_waze_WazeSoundRecorder_OnInfoListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
