/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_WazeSpeechttManagerBase */

#ifndef _Included_com_waze_WazeSpeechttManagerBase
#define _Included_com_waze_WazeSpeechttManagerBase
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_WazeSpeechttManagerBase_SPEECHTT_MAX_RESULTS
#define com_waze_WazeSpeechttManagerBase_SPEECHTT_MAX_RESULTS 1L
#undef com_waze_WazeSpeechttManagerBase_SPEECHTT_FLAG_TIMEOUT_ENABLED
#define com_waze_WazeSpeechttManagerBase_SPEECHTT_FLAG_TIMEOUT_ENABLED 1L
#undef com_waze_WazeSpeechttManagerBase_SPEECHTT_FLAG_INPUT_SEARCH
#define com_waze_WazeSpeechttManagerBase_SPEECHTT_FLAG_INPUT_SEARCH 2L
#undef com_waze_WazeSpeechttManagerBase_SPEECHTT_FLAG_INPUT_TEXT
#define com_waze_WazeSpeechttManagerBase_SPEECHTT_FLAG_INPUT_TEXT 4L
#undef com_waze_WazeSpeechttManagerBase_SPEECHTT_FLAG_INPUT_CMD
#define com_waze_WazeSpeechttManagerBase_SPEECHTT_FLAG_INPUT_CMD 8L
#undef com_waze_WazeSpeechttManagerBase_SPEECHTT_FLAG_EXTERNAL_RECOGNIZER
#define com_waze_WazeSpeechttManagerBase_SPEECHTT_FLAG_EXTERNAL_RECOGNIZER 16L
#undef com_waze_WazeSpeechttManagerBase_SPEECHTT_RES_STATUS_ERROR
#define com_waze_WazeSpeechttManagerBase_SPEECHTT_RES_STATUS_ERROR 0L
#undef com_waze_WazeSpeechttManagerBase_SPEECHTT_RES_STATUS_SUCCESS
#define com_waze_WazeSpeechttManagerBase_SPEECHTT_RES_STATUS_SUCCESS 1L
#undef com_waze_WazeSpeechttManagerBase_SPEECHTT_RES_STATUS_NO_RESULTS
#define com_waze_WazeSpeechttManagerBase_SPEECHTT_RES_STATUS_NO_RESULTS 2L
/*
 * Class:     com_waze_WazeSpeechttManagerBase
 * Method:    InitSpeechttManagerNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_WazeSpeechttManagerBase_InitSpeechttManagerNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_waze_WazeSpeechttManagerBase
 * Method:    SpeechttManagerCallbackNTV
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_waze_WazeSpeechttManagerBase_SpeechttManagerCallbackNTV
  (JNIEnv *, jobject, jlong, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_WazeSpeechttManagerBase_Callback */

#ifndef _Included_com_waze_WazeSpeechttManagerBase_Callback
#define _Included_com_waze_WazeSpeechttManagerBase_Callback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_WazeSpeechttManagerBase_OnOkMsgNoService */

#ifndef _Included_com_waze_WazeSpeechttManagerBase_OnOkMsgNoService
#define _Included_com_waze_WazeSpeechttManagerBase_OnOkMsgNoService
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
