/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_WazeResManager */

#ifndef _Included_com_waze_WazeResManager
#define _Included_com_waze_WazeResManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_WazeResManager_mVersionCodeSize
#define com_waze_WazeResManager_mVersionCodeSize 7L
#undef com_waze_WazeResManager_PROGRESS_DLG_SHOW_TIMEOUT
#define com_waze_WazeResManager_PROGRESS_DLG_SHOW_TIMEOUT 1000L
#undef com_waze_WazeResManager_SCREEN_HD_DIM_PIX
#define com_waze_WazeResManager_SCREEN_HD_DIM_PIX 640L
#undef com_waze_WazeResManager_SCREEN_LD_DIM_PIX
#define com_waze_WazeResManager_SCREEN_LD_DIM_PIX 240L
#undef com_waze_WazeResManager_EXTRACT_SKINS_BIN_FILES
#define com_waze_WazeResManager_EXTRACT_SKINS_BIN_FILES 0L
#undef com_waze_WazeResManager_EXTRACT_LIBRARY
#define com_waze_WazeResManager_EXTRACT_LIBRARY 0L
/*
 * Class:     com_waze_WazeResManager
 * Method:    InitResManagerNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_WazeResManager_InitResManagerNTV
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_WazeResManager_ResData */

#ifndef _Included_com_waze_WazeResManager_ResData
#define _Included_com_waze_WazeResManager_ResData
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_WazeResManager_ZipEntryType */

#ifndef _Included_com_waze_WazeResManager_ZipEntryType
#define _Included_com_waze_WazeResManager_ZipEntryType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
