/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_WazeMsgBox */

#ifndef _Included_com_waze_WazeMsgBox
#define _Included_com_waze_WazeMsgBox
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_WazeMsgBox_WAZE_MSG_BOX_RES_CANCEL
#define com_waze_WazeMsgBox_WAZE_MSG_BOX_RES_CANCEL 0L
#undef com_waze_WazeMsgBox_WAZE_MSG_BOX_RES_OK
#define com_waze_WazeMsgBox_WAZE_MSG_BOX_RES_OK 1L
/*
 * Class:     com_waze_WazeMsgBox
 * Method:    InitMsgBoxNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waze_WazeMsgBox_InitMsgBoxNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_waze_WazeMsgBox
 * Method:    MsgBoxCallbackNTV
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_waze_WazeMsgBox_MsgBoxCallbackNTV
  (JNIEnv *, jobject, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_WazeMsgBox_MsgBoxOnClick */

#ifndef _Included_com_waze_WazeMsgBox_MsgBoxOnClick
#define _Included_com_waze_WazeMsgBox_MsgBoxOnClick
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
