/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_WazeEditBox */

#ifndef _Included_com_waze_WazeEditBox
#define _Included_com_waze_WazeEditBox
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_WazeEditBox_WAZE_EDITBOX_FLAG_PASSWORD
#define com_waze_WazeEditBox_WAZE_EDITBOX_FLAG_PASSWORD 1L
#undef com_waze_WazeEditBox_WAZE_EDITBOX_FLAG_SPEECHTT
#define com_waze_WazeEditBox_WAZE_EDITBOX_FLAG_SPEECHTT 2L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_WazeEditBox_WazeEditBoxCallback */

#ifndef _Included_com_waze_WazeEditBox_WazeEditBoxCallback
#define _Included_com_waze_WazeEditBox_WazeEditBoxCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
