#ifndef     __ROADMAP_NET_DEFS_H__
#define     __ROADMAP_NET_DEFS_H__

#ifndef     CONNMGR_STATUS_UNKNOWN
   #define  CONNMGR_STATUS_UNKNOWN                    (0x00)
#endif   // CONNMGR_STATUS_UNKNOWN
#define     CONNMGR_STATUS_UNKNOWN_str                ("CONNMGR_STATUS_UNKNOWN")

#ifndef     CONNMGR_STATUS_CONNECTED
   #define  CONNMGR_STATUS_CONNECTED                  (0x10)
#endif   // CONNMGR_STATUS_CONNECTED
#define     CONNMGR_STATUS_CONNECTED_str              ("CONNMGR_STATUS_CONNECTED")

#ifndef     CONNMGR_STATUS_SUSPENDED
   #define  CONNMGR_STATUS_SUSPENDED                  (0x11)
#endif   // CONNMGR_STATUS_SUSPENDED
#define     CONNMGR_STATUS_SUSPENDED_str              ("CONNMGR_STATUS_SUSPENDED")

#ifndef     CONNMGR_STATUS_DISCONNECTED
   #define  CONNMGR_STATUS_DISCONNECTED               (0x20)
#endif   // CONNMGR_STATUS_DISCONNECTED
#define     CONNMGR_STATUS_DISCONNECTED_str           ("CONNMGR_STATUS_DISCONNECTED")

#ifndef     CONNMGR_STATUS_CONNECTIONFAILED
   #define  CONNMGR_STATUS_CONNECTIONFAILED           (0x21)
#endif   // CONNMGR_STATUS_CONNECTIONFAILED
#define     CONNMGR_STATUS_CONNECTIONFAILED_str       ("CONNMGR_STATUS_CONNECTIONFAILED")

#ifndef     CONNMGR_STATUS_CONNECTIONCANCELED
   #define  CONNMGR_STATUS_CONNECTIONCANCELED         (0x22)
#endif   // CONNMGR_STATUS_CONNECTIONCANCELED
#define     CONNMGR_STATUS_CONNECTIONCANCELED_str     ("CONNMGR_STATUS_CONNECTIONCANCELED")

#ifndef     CONNMGR_STATUS_CONNECTIONDISABLED
   #define  CONNMGR_STATUS_CONNECTIONDISABLED         (0x23)
#endif   // CONNMGR_STATUS_CONNECTIONDISABLED
#define     CONNMGR_STATUS_CONNECTIONDISABLED_str     ("CONNMGR_STATUS_CONNECTIONDISABLED")

#ifndef     CONNMGR_STATUS_NOPATHTODESTINATION
   #define  CONNMGR_STATUS_NOPATHTODESTINATION        (0x24)
#endif   // CONNMGR_STATUS_NOPATHTODESTINATION
#define     CONNMGR_STATUS_NOPATHTODESTINATION_str    ("CONNMGR_STATUS_NOPATHTODESTINATION")

#ifndef     CONNMGR_STATUS_WAITINGFORPATH
   #define  CONNMGR_STATUS_WAITINGFORPATH             (0x25)
#endif   // CONNMGR_STATUS_WAITINGFORPATH
#define     CONNMGR_STATUS_WAITINGFORPATH_str         ("CONNMGR_STATUS_WAITINGFORPATH")

#ifndef     CONNMGR_STATUS_WAITINGFORPHONE
   #define  CONNMGR_STATUS_WAITINGFORPHONE            (0x26)
#endif   // CONNMGR_STATUS_WAITINGFORPHONE
#define     CONNMGR_STATUS_WAITINGFORPHONE_str        ("CONNMGR_STATUS_WAITINGFORPHONE")

#ifndef     CONNMGR_STATUS_PHONEOFF
   #define  CONNMGR_STATUS_PHONEOFF                   (0x27)
#endif   // CONNMGR_STATUS_PHONEOFF
#define     CONNMGR_STATUS_PHONEOFF_str               ("CONNMGR_STATUS_PHONEOFF")

#ifndef     CONNMGR_STATUS_EXCLUSIVECONFLICT
   #define  CONNMGR_STATUS_EXCLUSIVECONFLICT          (0x28)
#endif   // CONNMGR_STATUS_EXCLUSIVECONFLICT
#define     CONNMGR_STATUS_EXCLUSIVECONFLICT_str      ("CONNMGR_STATUS_EXCLUSIVECONFLICT")

#ifndef     CONNMGR_STATUS_NORESOURCES
   #define  CONNMGR_STATUS_NORESOURCES                (0x29)
#endif   // CONNMGR_STATUS_NORESOURCES
#define     CONNMGR_STATUS_NORESOURCES_str            ("CONNMGR_STATUS_NORESOURCES")

#ifndef     CONNMGR_STATUS_CONNECTIONLINKFAILED
   #define  CONNMGR_STATUS_CONNECTIONLINKFAILED       (0x2A)
#endif   // CONNMGR_STATUS_CONNECTIONLINKFAILED
#define     CONNMGR_STATUS_CONNECTIONLINKFAILED_str   ("CONNMGR_STATUS_CONNECTIONLINKFAILED")

#ifndef     CONNMGR_STATUS_AUTHENTICATIONFAILED
   #define  CONNMGR_STATUS_AUTHENTICATIONFAILED       (0x2B)
#endif   // CONNMGR_STATUS_AUTHENTICATIONFAILED
#define     CONNMGR_STATUS_AUTHENTICATIONFAILED_str   ("CONNMGR_STATUS_AUTHENTICATIONFAILED")

#ifndef     CONNMGR_STATUS_WAITINGCONNECTION
   #define  CONNMGR_STATUS_WAITINGCONNECTION          (0x40)
#endif   // CONNMGR_STATUS_WAITINGCONNECTION
#define     CONNMGR_STATUS_WAITINGCONNECTION_str      ("CONNMGR_STATUS_WAITINGCONNECTION")

#ifndef     CONNMGR_STATUS_WAITINGFORRESOURCE
   #define  CONNMGR_STATUS_WAITINGFORRESOURCE         (0x41)
#endif   // CONNMGR_STATUS_WAITINGFORRESOURCE
#define     CONNMGR_STATUS_WAITINGFORRESOURCE_str     ("CONNMGR_STATUS_WAITINGFORRESOURCE")

#ifndef     CONNMGR_STATUS_WAITINGFORNETWORK
   #define  CONNMGR_STATUS_WAITINGFORNETWORK          (0x42)
#endif   // CONNMGR_STATUS_WAITINGFORNETWORK
#define     CONNMGR_STATUS_WAITINGFORNETWORK_str      ("CONNMGR_STATUS_WAITINGFORNETWORK")

#ifndef     CONNMGR_STATUS_WAITINGDISCONNECTION
   #define  CONNMGR_STATUS_WAITINGDISCONNECTION       (0x80)
#endif   // CONNMGR_STATUS_WAITINGDISCONNECTION
#define     CONNMGR_STATUS_WAITINGDISCONNECTION_str   ("CONNMGR_STATUS_WAITINGDISCONNECTION")

#ifndef     CONNMGR_STATUS_WAITINGCONNECTIONABORT
   #define  CONNMGR_STATUS_WAITINGCONNECTIONABORT     (0x81)
#endif   // CONNMGR_STATUS_WAITINGCONNECTIONABORT
#define     CONNMGR_STATUS_WAITINGCONNECTIONABORT_str ("CONNMGR_STATUS_WAITINGCONNECTIONABORT")

#define  CASE_STATUS_RETURN_STRING(_name_)            \
            case CONNMGR_STATUS_##_name_: return CONNMGR_STATUS_##_name_##_str;

const char* ConnMgr_GetStatusString( DWORD dwStatus);            

#endif   // __ROADMAP_NET_DEFS_H__